// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xajwxxghefkgscpjgngg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhhand4eGdoZWZrZ3NjcGpnbmdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNTQxOTAsImV4cCI6MjA4NTYzMDE5MH0.XmyPTcYpTCK1rTTP1pOYKczu5sZCTIxlShFJXazAH3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});